version: "3.8"
services:
  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    restart: unless-stopped
    ports:
    - '3000:3000'
    environment:
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_BASIC_ENABLED=false
    volumes:
    - ./grafana:/etc/grafana/provisioning/
    - ./dashboards_out:/var/dashboards_out/
volumes:
  grafana_storage: {}
